/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ResourceClaim references one entry in PodSpec.ResourceClaims.
 * @export
 * @interface K8sIoApiCoreV1ResourceClaim
 */
export interface K8sIoApiCoreV1ResourceClaim {
    /**
     * Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
     * @type {string}
     * @memberof K8sIoApiCoreV1ResourceClaim
     */
    name: string;
    /**
     * Request is the name chosen for a request in the referenced claim. If empty, everything from the claim is made available, otherwise only the result of this request.
     * @type {string}
     * @memberof K8sIoApiCoreV1ResourceClaim
     */
    request?: string;
}

/**
 * Check if a given object implements the K8sIoApiCoreV1ResourceClaim interface.
 */
export function instanceOfK8sIoApiCoreV1ResourceClaim(value: object): value is K8sIoApiCoreV1ResourceClaim {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function K8sIoApiCoreV1ResourceClaimFromJSON(json: any): K8sIoApiCoreV1ResourceClaim {
    return K8sIoApiCoreV1ResourceClaimFromJSONTyped(json, false);
}

export function K8sIoApiCoreV1ResourceClaimFromJSONTyped(json: any, ignoreDiscriminator: boolean): K8sIoApiCoreV1ResourceClaim {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'request': json['request'] == null ? undefined : json['request'],
    };
}

export function K8sIoApiCoreV1ResourceClaimToJSON(json: any): K8sIoApiCoreV1ResourceClaim {
    return K8sIoApiCoreV1ResourceClaimToJSONTyped(json, false);
}

export function K8sIoApiCoreV1ResourceClaimToJSONTyped(value?: K8sIoApiCoreV1ResourceClaim | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'request': value['request'],
    };
}

