/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1VirtualMachinePoolCondition } from '../models/V1alpha1VirtualMachinePoolCondition.js';
import { HttpFile } from '../http/http.js';

export class V1alpha1VirtualMachinePoolStatus {
    'conditions'?: Array<V1alpha1VirtualMachinePoolCondition>;
    /**
    * Canonical form of the label selector for HPA which consumes it through the scale subresource.
    */
    'labelSelector'?: string;
    'readyReplicas'?: number;
    'replicas'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<V1alpha1VirtualMachinePoolCondition>",
            "format": ""
        },
        {
            "name": "labelSelector",
            "baseName": "labelSelector",
            "type": "string",
            "format": ""
        },
        {
            "name": "readyReplicas",
            "baseName": "readyReplicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1VirtualMachinePoolStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
