/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1VirtualMachinePoolCondition } from './V1alpha1VirtualMachinePoolCondition';
import {
    V1alpha1VirtualMachinePoolConditionFromJSON,
    V1alpha1VirtualMachinePoolConditionFromJSONTyped,
    V1alpha1VirtualMachinePoolConditionToJSON,
    V1alpha1VirtualMachinePoolConditionToJSONTyped,
} from './V1alpha1VirtualMachinePoolCondition';

/**
 * 
 * @export
 * @interface V1alpha1VirtualMachinePoolStatus
 */
export interface V1alpha1VirtualMachinePoolStatus {
    /**
     * 
     * @type {Array<V1alpha1VirtualMachinePoolCondition>}
     * @memberof V1alpha1VirtualMachinePoolStatus
     */
    conditions?: Array<V1alpha1VirtualMachinePoolCondition>;
    /**
     * Canonical form of the label selector for HPA which consumes it through the scale subresource.
     * @type {string}
     * @memberof V1alpha1VirtualMachinePoolStatus
     */
    labelSelector?: string;
    /**
     * 
     * @type {number}
     * @memberof V1alpha1VirtualMachinePoolStatus
     */
    readyReplicas?: number;
    /**
     * 
     * @type {number}
     * @memberof V1alpha1VirtualMachinePoolStatus
     */
    replicas?: number;
}

/**
 * Check if a given object implements the V1alpha1VirtualMachinePoolStatus interface.
 */
export function instanceOfV1alpha1VirtualMachinePoolStatus(value: object): value is V1alpha1VirtualMachinePoolStatus {
    return true;
}

export function V1alpha1VirtualMachinePoolStatusFromJSON(json: any): V1alpha1VirtualMachinePoolStatus {
    return V1alpha1VirtualMachinePoolStatusFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachinePoolStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1VirtualMachinePoolStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(V1alpha1VirtualMachinePoolConditionFromJSON)),
        'labelSelector': json['labelSelector'] == null ? undefined : json['labelSelector'],
        'readyReplicas': json['readyReplicas'] == null ? undefined : json['readyReplicas'],
        'replicas': json['replicas'] == null ? undefined : json['replicas'],
    };
}

export function V1alpha1VirtualMachinePoolStatusToJSON(json: any): V1alpha1VirtualMachinePoolStatus {
    return V1alpha1VirtualMachinePoolStatusToJSONTyped(json, false);
}

export function V1alpha1VirtualMachinePoolStatusToJSONTyped(value?: V1alpha1VirtualMachinePoolStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(V1alpha1VirtualMachinePoolConditionToJSON)),
        'labelSelector': value['labelSelector'],
        'readyReplicas': value['readyReplicas'],
        'replicas': value['replicas'],
    };
}

