/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1alpha1VirtualMachinePoolCondition
 */
export interface V1alpha1VirtualMachinePoolCondition {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1VirtualMachinePoolCondition
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1VirtualMachinePoolCondition
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1VirtualMachinePoolCondition
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1VirtualMachinePoolCondition
     */
    type: string;
}

/**
 * Check if a given object implements the V1alpha1VirtualMachinePoolCondition interface.
 */
export function instanceOfV1alpha1VirtualMachinePoolCondition(value: object): value is V1alpha1VirtualMachinePoolCondition {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function V1alpha1VirtualMachinePoolConditionFromJSON(json: any): V1alpha1VirtualMachinePoolCondition {
    return V1alpha1VirtualMachinePoolConditionFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachinePoolConditionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): V1alpha1VirtualMachinePoolCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'status': json['status'],
        'type': json['type'],
    };
}

export function V1alpha1VirtualMachinePoolConditionToJSON(json: any): V1alpha1VirtualMachinePoolCondition {
    return V1alpha1VirtualMachinePoolConditionToJSONTyped(json, false);
}

export function V1alpha1VirtualMachinePoolConditionToJSONTyped(value?: V1alpha1VirtualMachinePoolCondition | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'reason': value['reason'],
        'status': value['status'],
        'type': value['type'],
    };
}

