/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { V1alpha1VirtualMachineCloneSpec } from './V1alpha1VirtualMachineCloneSpec.js';
import {
    V1alpha1VirtualMachineCloneSpecFromJSON,
    V1alpha1VirtualMachineCloneSpecFromJSONTyped,
    V1alpha1VirtualMachineCloneSpecToJSON,
    V1alpha1VirtualMachineCloneSpecToJSONTyped,
} from './V1alpha1VirtualMachineCloneSpec.js';
import type { V1alpha1VirtualMachineCloneStatus } from './V1alpha1VirtualMachineCloneStatus.js';
import {
    V1alpha1VirtualMachineCloneStatusFromJSON,
    V1alpha1VirtualMachineCloneStatusFromJSONTyped,
    V1alpha1VirtualMachineCloneStatusToJSON,
    V1alpha1VirtualMachineCloneStatusToJSONTyped,
} from './V1alpha1VirtualMachineCloneStatus.js';
import type { K8sIoApimachineryPkgApisMetaV1ObjectMeta } from './K8sIoApimachineryPkgApisMetaV1ObjectMeta.js';
import {
    K8sIoApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    K8sIoApimachineryPkgApisMetaV1ObjectMetaFromJSONTyped,
    K8sIoApimachineryPkgApisMetaV1ObjectMetaToJSON,
    K8sIoApimachineryPkgApisMetaV1ObjectMetaToJSONTyped,
} from './K8sIoApimachineryPkgApisMetaV1ObjectMeta.js';

/**
 * VirtualMachineClone is a CRD that clones one VM into another.
 * @export
 * @interface V1alpha1VirtualMachineClone
 */
export interface V1alpha1VirtualMachineClone {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1VirtualMachineClone
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1VirtualMachineClone
     */
    kind?: string;
    /**
     * 
     * @type {K8sIoApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof V1alpha1VirtualMachineClone
     */
    metadata?: K8sIoApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {V1alpha1VirtualMachineCloneSpec}
     * @memberof V1alpha1VirtualMachineClone
     */
    spec: V1alpha1VirtualMachineCloneSpec;
    /**
     * 
     * @type {V1alpha1VirtualMachineCloneStatus}
     * @memberof V1alpha1VirtualMachineClone
     */
    status?: V1alpha1VirtualMachineCloneStatus;
}

/**
 * Check if a given object implements the V1alpha1VirtualMachineClone interface.
 */
export function instanceOfV1alpha1VirtualMachineClone(value: object): value is V1alpha1VirtualMachineClone {
    if (!('spec' in value) || value['spec'] === undefined) return false;
    return true;
}

export function V1alpha1VirtualMachineCloneFromJSON(json: any): V1alpha1VirtualMachineClone {
    return V1alpha1VirtualMachineCloneFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachineCloneFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha1VirtualMachineClone {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : K8sIoApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': V1alpha1VirtualMachineCloneSpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : V1alpha1VirtualMachineCloneStatusFromJSON(json['status']),
    };
}

export function V1alpha1VirtualMachineCloneToJSON(json: any): V1alpha1VirtualMachineClone {
    return V1alpha1VirtualMachineCloneToJSONTyped(json, false);
}

export function V1alpha1VirtualMachineCloneToJSONTyped(value?: V1alpha1VirtualMachineClone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'metadata': K8sIoApimachineryPkgApisMetaV1ObjectMetaToJSON(value['metadata']),
        'spec': V1alpha1VirtualMachineCloneSpecToJSON(value['spec']),
        'status': V1alpha1VirtualMachineCloneStatusToJSON(value['status']),
    };
}

