/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class V1ArchSpecificConfiguration {
    'emulatedMachines'?: Array<string>;
    'machineType'?: string;
    'ovmfPath'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emulatedMachines",
            "baseName": "emulatedMachines",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "machineType",
            "baseName": "machineType",
            "type": "string",
            "format": ""
        },
        {
            "name": "ovmfPath",
            "baseName": "ovmfPath",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ArchSpecificConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
