/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1FeatureAPIC } from '../models/V1FeatureAPIC.js';
import { V1FeatureHyperv } from '../models/V1FeatureHyperv.js';
import { V1FeatureKVM } from '../models/V1FeatureKVM.js';
import { V1FeatureState } from '../models/V1FeatureState.js';
import { HttpFile } from '../http/http.js';

/**
* FeaturePreferences contains various optional defaults for Features.
*/
export class V1beta1FeaturePreferences {
    'preferredAcpi'?: V1FeatureState;
    'preferredApic'?: V1FeatureAPIC;
    'preferredHyperv'?: V1FeatureHyperv;
    'preferredKvm'?: V1FeatureKVM;
    'preferredPvspinlock'?: V1FeatureState;
    'preferredSmm'?: V1FeatureState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "preferredAcpi",
            "baseName": "preferredAcpi",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "preferredApic",
            "baseName": "preferredApic",
            "type": "V1FeatureAPIC",
            "format": ""
        },
        {
            "name": "preferredHyperv",
            "baseName": "preferredHyperv",
            "type": "V1FeatureHyperv",
            "format": ""
        },
        {
            "name": "preferredKvm",
            "baseName": "preferredKvm",
            "type": "V1FeatureKVM",
            "format": ""
        },
        {
            "name": "preferredPvspinlock",
            "baseName": "preferredPvspinlock",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "preferredSmm",
            "baseName": "preferredSmm",
            "type": "V1FeatureState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1beta1FeaturePreferences.attributeTypeMap;
    }

    public constructor() {
    }
}
