/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1beta1CPUPreferenceRequirement } from '../models/V1beta1CPUPreferenceRequirement.js';
import { V1beta1MemoryPreferenceRequirement } from '../models/V1beta1MemoryPreferenceRequirement.js';
import { HttpFile } from '../http/http.js';

export class V1beta1PreferenceRequirements {
    'cpu'?: V1beta1CPUPreferenceRequirement;
    'memory'?: V1beta1MemoryPreferenceRequirement;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "V1beta1CPUPreferenceRequirement",
            "format": ""
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "V1beta1MemoryPreferenceRequirement",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1beta1PreferenceRequirements.attributeTypeMap;
    }

    public constructor() {
    }
}
