/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1beta1Condition } from '../models/V1beta1Condition.js';
import { V1beta1Error } from '../models/V1beta1Error.js';
import { V1beta1SnapshotVolumesLists } from '../models/V1beta1SnapshotVolumesLists.js';
import { HttpFile } from '../http/http.js';

/**
* VirtualMachineSnapshotStatus is the status for a VirtualMachineSnapshot resource
*/
export class V1beta1VirtualMachineSnapshotStatus {
    'conditions'?: Array<V1beta1Condition>;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'creationTime'?: string;
    'error'?: V1beta1Error;
    'indications'?: Array<string>;
    'phase'?: string;
    'readyToUse'?: boolean;
    'snapshotVolumes'?: V1beta1SnapshotVolumesLists;
    'sourceUID'?: string;
    'virtualMachineSnapshotContentName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<V1beta1Condition>",
            "format": ""
        },
        {
            "name": "creationTime",
            "baseName": "creationTime",
            "type": "string",
            "format": "date-time"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "V1beta1Error",
            "format": ""
        },
        {
            "name": "indications",
            "baseName": "indications",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "phase",
            "baseName": "phase",
            "type": "string",
            "format": ""
        },
        {
            "name": "readyToUse",
            "baseName": "readyToUse",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "snapshotVolumes",
            "baseName": "snapshotVolumes",
            "type": "V1beta1SnapshotVolumesLists",
            "format": ""
        },
        {
            "name": "sourceUID",
            "baseName": "sourceUID",
            "type": "string",
            "format": ""
        },
        {
            "name": "virtualMachineSnapshotContentName",
            "baseName": "virtualMachineSnapshotContentName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1beta1VirtualMachineSnapshotStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
