/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1beta1Condition } from '../models/V1beta1Condition.js';
import { V1beta1VolumeRestore } from '../models/V1beta1VolumeRestore.js';
import { HttpFile } from '../http/http.js';

/**
* VirtualMachineRestoreStatus is the spec for a VirtualMachineRestoreresource
*/
export class V1beta1VirtualMachineRestoreStatus {
    'complete'?: boolean;
    'conditions'?: Array<V1beta1Condition>;
    'deletedDataVolumes'?: Array<string>;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'restoreTime'?: string;
    'restores'?: Array<V1beta1VolumeRestore>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<V1beta1Condition>",
            "format": ""
        },
        {
            "name": "deletedDataVolumes",
            "baseName": "deletedDataVolumes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "restoreTime",
            "baseName": "restoreTime",
            "type": "string",
            "format": "date-time"
        },
        {
            "name": "restores",
            "baseName": "restores",
            "type": "Array<V1beta1VolumeRestore>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1beta1VirtualMachineRestoreStatus.attributeTypeMap;
    }

    public constructor() {
    }
}
