/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1BIOS } from '../models/V1BIOS.js';
import { V1EFI } from '../models/V1EFI.js';
import { HttpFile } from '../http/http.js';

/**
* Represents the firmware blob used to assist in the domain creation process. Used for setting the QEMU BIOS file path for the libvirt domain.
*/
export class V1Bootloader {
    'bios'?: V1BIOS;
    'efi'?: V1EFI;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bios",
            "baseName": "bios",
            "type": "V1BIOS",
            "format": ""
        },
        {
            "name": "efi",
            "baseName": "efi",
            "type": "V1EFI",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Bootloader.attributeTypeMap;
    }

    public constructor() {
    }
}
