/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ClockOffsetUTC } from '../models/V1ClockOffsetUTC.js';
import { HttpFile } from '../http/http.js';

/**
* Exactly one of its members must be set.
*/
export class V1ClockOffset {
    /**
    * Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. \'America/New_York\').
    */
    'timezone'?: string;
    'utc'?: V1ClockOffsetUTC;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "utc",
            "baseName": "utc",
            "type": "V1ClockOffsetUTC",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ClockOffset.attributeTypeMap;
    }

    public constructor() {
    }
}
