/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CustomizeComponentsPatch } from '../models/V1CustomizeComponentsPatch.js';
import { V1Flags } from '../models/V1Flags.js';
import { HttpFile } from '../http/http.js';

export class V1CustomizeComponents {
    'flags'?: V1Flags;
    'patches'?: Array<V1CustomizeComponentsPatch>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "flags",
            "baseName": "flags",
            "type": "V1Flags",
            "format": ""
        },
        {
            "name": "patches",
            "baseName": "patches",
            "type": "Array<V1CustomizeComponentsPatch>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1CustomizeComponents.attributeTypeMap;
    }

    public constructor() {
    }
}
