/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class V1DataVolumeSource {
    /**
    * Hotpluggable indicates whether the volume can be hotplugged and hotunplugged.
    */
    'hotpluggable'?: boolean;
    /**
    * Name of both the DataVolume and the PVC in the same namespace. After PVC population the DataVolume is garbage collected by default.
    */
    'name': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hotpluggable",
            "baseName": "hotpluggable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1DataVolumeSource.attributeTypeMap;
    }

    public constructor() {
    }
}
