/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CPU } from '../models/V1CPU.js';
import { V1Chassis } from '../models/V1Chassis.js';
import { V1Clock } from '../models/V1Clock.js';
import { V1Devices } from '../models/V1Devices.js';
import { V1Features } from '../models/V1Features.js';
import { V1Firmware } from '../models/V1Firmware.js';
import { V1LaunchSecurity } from '../models/V1LaunchSecurity.js';
import { V1Machine } from '../models/V1Machine.js';
import { V1Memory } from '../models/V1Memory.js';
import { V1ResourceRequirements } from '../models/V1ResourceRequirements.js';
import { HttpFile } from '../http/http.js';

export class V1DomainSpec {
    'chassis'?: V1Chassis;
    'clock'?: V1Clock;
    'cpu'?: V1CPU;
    'devices': V1Devices;
    'features'?: V1Features;
    'firmware'?: V1Firmware;
    /**
    * Controls whether or not disks will share IOThreads. Omitting IOThreadsPolicy disables use of IOThreads. One of: shared, auto
    */
    'ioThreadsPolicy'?: string;
    'launchSecurity'?: V1LaunchSecurity;
    'machine'?: V1Machine;
    'memory'?: V1Memory;
    'resources'?: V1ResourceRequirements;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chassis",
            "baseName": "chassis",
            "type": "V1Chassis",
            "format": ""
        },
        {
            "name": "clock",
            "baseName": "clock",
            "type": "V1Clock",
            "format": ""
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "V1CPU",
            "format": ""
        },
        {
            "name": "devices",
            "baseName": "devices",
            "type": "V1Devices",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "V1Features",
            "format": ""
        },
        {
            "name": "firmware",
            "baseName": "firmware",
            "type": "V1Firmware",
            "format": ""
        },
        {
            "name": "ioThreadsPolicy",
            "baseName": "ioThreadsPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "launchSecurity",
            "baseName": "launchSecurity",
            "type": "V1LaunchSecurity",
            "format": ""
        },
        {
            "name": "machine",
            "baseName": "machine",
            "type": "V1Machine",
            "format": ""
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "V1Memory",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "V1ResourceRequirements",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1DomainSpec.attributeTypeMap;
    }

    public constructor() {
    }
}
