/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApiCoreV1PersistentVolumeClaimVolumeSource } from '../models/K8sIoApiCoreV1PersistentVolumeClaimVolumeSource.js';
import { HttpFile } from '../http/http.js';

export class V1EphemeralVolumeSource {
    'persistentVolumeClaim'?: K8sIoApiCoreV1PersistentVolumeClaimVolumeSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "persistentVolumeClaim",
            "baseName": "persistentVolumeClaim",
            "type": "K8sIoApiCoreV1PersistentVolumeClaimVolumeSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1EphemeralVolumeSource.attributeTypeMap;
    }

    public constructor() {
    }
}
