/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1FeatureAPIC } from '../models/V1FeatureAPIC.js';
import { V1FeatureHyperv } from '../models/V1FeatureHyperv.js';
import { V1FeatureKVM } from '../models/V1FeatureKVM.js';
import { V1FeatureState } from '../models/V1FeatureState.js';
import { V1HyperVPassthrough } from '../models/V1HyperVPassthrough.js';
import { HttpFile } from '../http/http.js';

export class V1Features {
    'acpi'?: V1FeatureState;
    'apic'?: V1FeatureAPIC;
    'hyperv'?: V1FeatureHyperv;
    'hypervPassthrough'?: V1HyperVPassthrough;
    'kvm'?: V1FeatureKVM;
    'pvspinlock'?: V1FeatureState;
    'smm'?: V1FeatureState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "acpi",
            "baseName": "acpi",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "apic",
            "baseName": "apic",
            "type": "V1FeatureAPIC",
            "format": ""
        },
        {
            "name": "hyperv",
            "baseName": "hyperv",
            "type": "V1FeatureHyperv",
            "format": ""
        },
        {
            "name": "hypervPassthrough",
            "baseName": "hypervPassthrough",
            "type": "V1HyperVPassthrough",
            "format": ""
        },
        {
            "name": "kvm",
            "baseName": "kvm",
            "type": "V1FeatureKVM",
            "format": ""
        },
        {
            "name": "pvspinlock",
            "baseName": "pvspinlock",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "smm",
            "baseName": "smm",
            "type": "V1FeatureState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Features.attributeTypeMap;
    }

    public constructor() {
    }
}
