/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VGPUOptions } from '../models/V1VGPUOptions.js';
import { HttpFile } from '../http/http.js';

export class V1GPU {
    'deviceName': string;
    /**
    * Name of the GPU device as exposed by a device plugin
    */
    'name': string;
    /**
    * If specified, the virtual network interface address and its tag will be provided to the guest via config drive
    */
    'tag'?: string;
    'virtualGPUOptions'?: V1VGPUOptions;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deviceName",
            "baseName": "deviceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "virtualGPUOptions",
            "baseName": "virtualGPUOptions",
            "type": "V1VGPUOptions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1GPU.attributeTypeMap;
    }

    public constructor() {
    }
}
