/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApimachineryPkgApisMetaV1LabelSelector } from '../models/K8sIoApimachineryPkgApisMetaV1LabelSelector.js';
import { HttpFile } from '../http/http.js';

/**
* KSMConfiguration holds information about KSM.
*/
export class V1KSMConfiguration {
    'nodeLabelSelector'?: K8sIoApimachineryPkgApisMetaV1LabelSelector;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeLabelSelector",
            "baseName": "nodeLabelSelector",
            "type": "K8sIoApimachineryPkgApisMetaV1LabelSelector",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1KSMConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
