/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeMediatedDeviceTypesConfig } from '../models/V1NodeMediatedDeviceTypesConfig.js';
import { HttpFile } from '../http/http.js';

/**
* MediatedDevicesConfiguration holds information about MDEV types to be defined, if available
*/
export class V1MediatedDevicesConfiguration {
    'mediatedDeviceTypes'?: Array<string>;
    /**
    * Deprecated. Use mediatedDeviceTypes instead.
    */
    'mediatedDevicesTypes'?: Array<string>;
    'nodeMediatedDeviceTypes'?: Array<V1NodeMediatedDeviceTypesConfig>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mediatedDeviceTypes",
            "baseName": "mediatedDeviceTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mediatedDevicesTypes",
            "baseName": "mediatedDevicesTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "nodeMediatedDeviceTypes",
            "baseName": "nodeMediatedDeviceTypes",
            "type": "Array<V1NodeMediatedDeviceTypesConfig>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1MediatedDevicesConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
