/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1SEVPolicy } from '../models/V1SEVPolicy.js';
import { HttpFile } from '../http/http.js';

export class V1SEV {
    'attestation'?: any;
    /**
    * Base64 encoded guest owner\'s Diffie-Hellman key.
    */
    'dhCert'?: string;
    'policy'?: V1SEVPolicy;
    /**
    * Base64 encoded session blob.
    */
    'session'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attestation",
            "baseName": "attestation",
            "type": "any",
            "format": ""
        },
        {
            "name": "dhCert",
            "baseName": "dhCert",
            "type": "string",
            "format": ""
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "V1SEVPolicy",
            "format": ""
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1SEV.attributeTypeMap;
    }

    public constructor() {
    }
}
