/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* SEVSecretOptions is used to provide a secret for a running guest.
*/
export class V1SEVSecretOptions {
    /**
    * Base64 encoded header needed to decrypt the secret.
    */
    'header'?: string;
    /**
    * Base64 encoded encrypted launch secret.
    */
    'secret'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "header",
            "baseName": "header",
            "type": "string",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1SEVSecretOptions.attributeTypeMap;
    }

    public constructor() {
    }
}
