/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1VirtualMachineInstanceMigrationSpec
 */
export interface V1VirtualMachineInstanceMigrationSpec {
    /**
     * The name of the VMI to perform the migration on. VMI must exist in the migration objects namespace
     * @type {string}
     * @memberof V1VirtualMachineInstanceMigrationSpec
     */
    vmiName?: string;
}

/**
 * Check if a given object implements the V1VirtualMachineInstanceMigrationSpec interface.
 */
export function instanceOfV1VirtualMachineInstanceMigrationSpec(value: object): value is V1VirtualMachineInstanceMigrationSpec {
    return true;
}

export function V1VirtualMachineInstanceMigrationSpecFromJSON(json: any): V1VirtualMachineInstanceMigrationSpec {
    return V1VirtualMachineInstanceMigrationSpecFromJSONTyped(json, false);
}

export function V1VirtualMachineInstanceMigrationSpecFromJSONTyped(json: any, _ignoreDiscriminator: boolean): V1VirtualMachineInstanceMigrationSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'vmiName': json['vmiName'] == null ? undefined : json['vmiName'],
    };
}

export function V1VirtualMachineInstanceMigrationSpecToJSON(json: any): V1VirtualMachineInstanceMigrationSpec {
    return V1VirtualMachineInstanceMigrationSpecToJSONTyped(json, false);
}

export function V1VirtualMachineInstanceMigrationSpecToJSONTyped(value?: V1VirtualMachineInstanceMigrationSpec | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vmiName': value['vmiName'],
    };
}

