/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CloudInitConfigDriveSource } from '../models/V1CloudInitConfigDriveSource.js';
import { V1CloudInitNoCloudSource } from '../models/V1CloudInitNoCloudSource.js';
import { V1ConfigMapVolumeSource } from '../models/V1ConfigMapVolumeSource.js';
import { V1ContainerDiskSource } from '../models/V1ContainerDiskSource.js';
import { V1DataVolumeSource } from '../models/V1DataVolumeSource.js';
import { V1DownwardAPIVolumeSource } from '../models/V1DownwardAPIVolumeSource.js';
import { V1EmptyDiskSource } from '../models/V1EmptyDiskSource.js';
import { V1EphemeralVolumeSource } from '../models/V1EphemeralVolumeSource.js';
import { V1HostDisk } from '../models/V1HostDisk.js';
import { V1MemoryDumpVolumeSource } from '../models/V1MemoryDumpVolumeSource.js';
import { V1PersistentVolumeClaimVolumeSource } from '../models/V1PersistentVolumeClaimVolumeSource.js';
import { V1SecretVolumeSource } from '../models/V1SecretVolumeSource.js';
import { V1ServiceAccountVolumeSource } from '../models/V1ServiceAccountVolumeSource.js';
import { V1SysprepSource } from '../models/V1SysprepSource.js';
import { HttpFile } from '../http/http.js';

/**
* Volume represents a named volume in a vmi.
*/
export class V1Volume {
    'cloudInitConfigDrive'?: V1CloudInitConfigDriveSource;
    'cloudInitNoCloud'?: V1CloudInitNoCloudSource;
    'configMap'?: V1ConfigMapVolumeSource;
    'containerDisk'?: V1ContainerDiskSource;
    'dataVolume'?: V1DataVolumeSource;
    'downwardAPI'?: V1DownwardAPIVolumeSource;
    /**
    * DownwardMetricsVolumeSource adds a very small disk to VMIs which contains a limited view of host and guest metrics. The disk content is compatible with vhostmd (https://github.com/vhostmd/vhostmd) and vm-dump-metrics.
    */
    'downwardMetrics'?: any;
    'emptyDisk'?: V1EmptyDiskSource;
    'ephemeral'?: V1EphemeralVolumeSource;
    'hostDisk'?: V1HostDisk;
    'memoryDump'?: V1MemoryDumpVolumeSource;
    /**
    * Volume\'s name. Must be a DNS_LABEL and unique within the vmi. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    */
    'name': string;
    'persistentVolumeClaim'?: V1PersistentVolumeClaimVolumeSource;
    'secret'?: V1SecretVolumeSource;
    'serviceAccount'?: V1ServiceAccountVolumeSource;
    'sysprep'?: V1SysprepSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cloudInitConfigDrive",
            "baseName": "cloudInitConfigDrive",
            "type": "V1CloudInitConfigDriveSource",
            "format": ""
        },
        {
            "name": "cloudInitNoCloud",
            "baseName": "cloudInitNoCloud",
            "type": "V1CloudInitNoCloudSource",
            "format": ""
        },
        {
            "name": "configMap",
            "baseName": "configMap",
            "type": "V1ConfigMapVolumeSource",
            "format": ""
        },
        {
            "name": "containerDisk",
            "baseName": "containerDisk",
            "type": "V1ContainerDiskSource",
            "format": ""
        },
        {
            "name": "dataVolume",
            "baseName": "dataVolume",
            "type": "V1DataVolumeSource",
            "format": ""
        },
        {
            "name": "downwardAPI",
            "baseName": "downwardAPI",
            "type": "V1DownwardAPIVolumeSource",
            "format": ""
        },
        {
            "name": "downwardMetrics",
            "baseName": "downwardMetrics",
            "type": "any",
            "format": ""
        },
        {
            "name": "emptyDisk",
            "baseName": "emptyDisk",
            "type": "V1EmptyDiskSource",
            "format": ""
        },
        {
            "name": "ephemeral",
            "baseName": "ephemeral",
            "type": "V1EphemeralVolumeSource",
            "format": ""
        },
        {
            "name": "hostDisk",
            "baseName": "hostDisk",
            "type": "V1HostDisk",
            "format": ""
        },
        {
            "name": "memoryDump",
            "baseName": "memoryDump",
            "type": "V1MemoryDumpVolumeSource",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "persistentVolumeClaim",
            "baseName": "persistentVolumeClaim",
            "type": "V1PersistentVolumeClaimVolumeSource",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "V1SecretVolumeSource",
            "format": ""
        },
        {
            "name": "serviceAccount",
            "baseName": "serviceAccount",
            "type": "V1ServiceAccountVolumeSource",
            "format": ""
        },
        {
            "name": "sysprep",
            "baseName": "sysprep",
            "type": "V1SysprepSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Volume.attributeTypeMap;
    }

    public constructor() {
    }
}
