/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VolumeMigrationState } from '../models/V1VolumeMigrationState.js';
import { HttpFile } from '../http/http.js';

export class V1VolumeUpdateState {
    'volumeMigrationState'?: V1VolumeMigrationState;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "volumeMigrationState",
            "baseName": "volumeMigrationState",
            "type": "V1VolumeMigrationState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeUpdateState.attributeTypeMap;
    }

    public constructor() {
    }
}
